### ISSUE TITLE
Update to latest `scenedetect` API

### ISSUE THREAD

**Issue by Breakthrough** [tin2tin/shot_detection#3]
Hi @tin2tin;

I noticed your project is still using an older version of the PySceneDetect API.  You may want to include a requirements.txt file which states the version of PySceneDetect it works with.  To update to the new API, see the following code snippet:

https://github.com/Breakthrough/PySceneDetect/blob/93aed414c5a33add079dbba54bdaf2595ea5b431/tests/test_api.py#L47-L60

The only difference from what you have now is using `open_video()` instead of `VideoManager`, and the difference in how start/end time is handled.

Thanks!

**Comment by tin2tin** [comment]
Thank you for the heads-up. I've updated it, so it seems to be working with the latest PySceneDetect API. However, I do not think the way deals with python will allow for requirements.txt files.
